/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBack: typeof import('./src/components/AppBack.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppLocaleSwitch: typeof import('./src/components/AppLocaleSwitch.vue')['default']
    AppSideMenu: typeof import('./src/components/AppSideMenu.vue')['default']
    AppThemeSwitch: typeof import('./src/components/AppThemeSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterStack: typeof import('./src/components/RouterStack.vue')['default']
    RouterStackView: typeof import('./src/components/RouterStackView.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarAvatarGroup: typeof import('@varlet/ui')['_AvatarGroupComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarCollapse: typeof import('@varlet/ui')['_CollapseComponent']
    VarCollapseItem: typeof import('@varlet/ui')['_CollapseItemComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarEllipsis: typeof import('@varlet/ui')['_EllipsisComponent']
    VarFab: typeof import('@varlet/ui')['_FabComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarPullRefresh: typeof import('@varlet/ui')['_PullRefreshComponent']
    VarRate: typeof import('@varlet/ui')['_RateComponent']
    VarSlider: typeof import('@varlet/ui')['_SliderComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
