/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/layout': RouteRecordInfo<'/layout', '/layout', Record<never, never>, Record<never, never>>,
    '/layout/home': RouteRecordInfo<'/layout/home', '/layout/home', Record<never, never>, Record<never, never>>,
    '/layout/home/detail': RouteRecordInfo<'/layout/home/detail', '/layout/home/detail', Record<never, never>, Record<never, never>>,
    '/layout/home/settings': RouteRecordInfo<'/layout/home/settings', '/layout/home/settings', Record<never, never>, Record<never, never>>,
    '/layout/home/sign-in': RouteRecordInfo<'/layout/home/sign-in', '/layout/home/sign-in', Record<never, never>, Record<never, never>>,
    '/layout/home/sign-in/forgot-password': RouteRecordInfo<'/layout/home/sign-in/forgot-password', '/layout/home/sign-in/forgot-password', Record<never, never>, Record<never, never>>,
    '/layout/home/sign-in/sign-up': RouteRecordInfo<'/layout/home/sign-in/sign-up', '/layout/home/sign-in/sign-up', Record<never, never>, Record<never, never>>,
    '/layout/home/sign-up': RouteRecordInfo<'/layout/home/sign-up', '/layout/home/sign-up', Record<never, never>, Record<never, never>>,
    '/layout/message': RouteRecordInfo<'/layout/message', '/layout/message', Record<never, never>, Record<never, never>>,
    '/layout/message/settings': RouteRecordInfo<'/layout/message/settings', '/layout/message/settings', Record<never, never>, Record<never, never>>,
    '/layout/message/sign-in': RouteRecordInfo<'/layout/message/sign-in', '/layout/message/sign-in', Record<never, never>, Record<never, never>>,
    '/layout/message/sign-in/forgot-password': RouteRecordInfo<'/layout/message/sign-in/forgot-password', '/layout/message/sign-in/forgot-password', Record<never, never>, Record<never, never>>,
    '/layout/message/sign-in/sign-up': RouteRecordInfo<'/layout/message/sign-in/sign-up', '/layout/message/sign-in/sign-up', Record<never, never>, Record<never, never>>,
    '/layout/message/sign-up': RouteRecordInfo<'/layout/message/sign-up', '/layout/message/sign-up', Record<never, never>, Record<never, never>>,
    '/layout/profile': RouteRecordInfo<'/layout/profile', '/layout/profile', Record<never, never>, Record<never, never>>,
    '/layout/profile/settings': RouteRecordInfo<'/layout/profile/settings', '/layout/profile/settings', Record<never, never>, Record<never, never>>,
    '/layout/profile/sign-in': RouteRecordInfo<'/layout/profile/sign-in', '/layout/profile/sign-in', Record<never, never>, Record<never, never>>,
    '/layout/profile/sign-in/forgot-password': RouteRecordInfo<'/layout/profile/sign-in/forgot-password', '/layout/profile/sign-in/forgot-password', Record<never, never>, Record<never, never>>,
    '/layout/profile/sign-in/sign-up': RouteRecordInfo<'/layout/profile/sign-in/sign-up', '/layout/profile/sign-in/sign-up', Record<never, never>, Record<never, never>>,
    '/layout/profile/sign-up': RouteRecordInfo<'/layout/profile/sign-up', '/layout/profile/sign-up', Record<never, never>, Record<never, never>>,
    '/layout/topic': RouteRecordInfo<'/layout/topic', '/layout/topic', Record<never, never>, Record<never, never>>,
    '/layout/topic/settings': RouteRecordInfo<'/layout/topic/settings', '/layout/topic/settings', Record<never, never>, Record<never, never>>,
    '/layout/topic/sign-in': RouteRecordInfo<'/layout/topic/sign-in', '/layout/topic/sign-in', Record<never, never>, Record<never, never>>,
    '/layout/topic/sign-in/forgot-password': RouteRecordInfo<'/layout/topic/sign-in/forgot-password', '/layout/topic/sign-in/forgot-password', Record<never, never>, Record<never, never>>,
    '/layout/topic/sign-in/sign-up': RouteRecordInfo<'/layout/topic/sign-in/sign-up', '/layout/topic/sign-in/sign-up', Record<never, never>, Record<never, never>>,
    '/layout/topic/sign-up': RouteRecordInfo<'/layout/topic/sign-up', '/layout/topic/sign-up', Record<never, never>, Record<never, never>>,
    '/stacks/detail': RouteRecordInfo<'/stacks/detail', '/stacks/detail', Record<never, never>, Record<never, never>>,
    '/stacks/forgot-password': RouteRecordInfo<'/stacks/forgot-password', '/stacks/forgot-password', Record<never, never>, Record<never, never>>,
    '/stacks/settings': RouteRecordInfo<'/stacks/settings', '/stacks/settings', Record<never, never>, Record<never, never>>,
    '/stacks/sign-in': RouteRecordInfo<'/stacks/sign-in', '/stacks/sign-in', Record<never, never>, Record<never, never>>,
    '/stacks/sign-up': RouteRecordInfo<'/stacks/sign-up', '/stacks/sign-up', Record<never, never>, Record<never, never>>,
  }
}
